BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "TB_TANQUE" (
	"ID"	INTEGER NOT NULL,
	"DESCRICAO"	TEXT NOT NULL,
	"CAPACIDAD"	NUMERIC(14, 3) NOT NULL,
	"TIPO"	INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "TB_BOMBA" (
	"ID"	INTEGER NOT NULL,
	"DESCRICAO"	TEXT NOT NULL,
	"ID_TANQUE"	INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("ID_TANQUE") REFERENCES "TB_TANQUE"("ID")
);
CREATE TABLE IF NOT EXISTS "TB_PRECOS" (
	"ID"	INTEGER NOT NULL,
	"VLR_LITRO_GAS"	NUMERIC(14, 2) NOT NULL,
	"VLR_LITRO_OLE"	NUMERIC(14, 2) NOT NULL,
	"VLR_IMPOSTO"	NUMERIC(14, 2) NOT NULL,
	"VIGENTE"	INTEGER NOT NULL DEFAULT 1,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "TB_MOVIMENTO" (
	"ID"	INTEGER NOT NULL,
	"DTHR"	TEXT NOT NULL,
	"LITROS"	NUMERIC(14, 3) NOT NULL,
	"VLR_TOTAL"	NUMERIC(14, 2) NOT NULL,
	"VLR_IMPOSTO"	NUMERIC(14, 2) NOT NULL,
	"ID_BOMBA"	INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("ID_BOMBA") REFERENCES "TB_BOMBA"("ID")
);
COMMIT;
